name: Deploy eCommerce Website

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:pr-${{ github.event.number }}
        push: true

    - name: Deploy to EC2
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:pr-${{ github.event.number }}
        docker stop ecommerce-website || true
        docker rm ecommerce-website || true
        docker run -d -p 80:80 --name ecommerce-website ${{ secrets.DOCKER_USERNAME }}/ecommerce-website:pr-${{ github.event.number }}

    - name: Comment on PR
      uses: peter-evans/commit-comment@v2
      with:
        body: |
          :rocket: The deployment of your PR is complete!
          View it at: http://${{ secrets.EC2_HOST }}

